// <auto-generated />
using System;
using DA_Framewrok.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DA_Framewrok.Migrations
{
    [DbContext(typeof(TrungtamtienganhContext))]
    partial class TrungtamtienganhContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DA_Framewrok.Models.Buoihoc", b =>
                {
                    b.Property<int>("Mabuoihoc")
                        .HasColumnType("int")
                        .HasColumnName("MABUOIHOC");

                    b.Property<string>("Domain")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DOMAIN");

                    b.Property<int?>("Malophoc")
                        .HasColumnType("int")
                        .HasColumnName("MALOPHOC");

                    b.Property<DateOnly?>("Ngaytao")
                        .HasColumnType("date")
                        .HasColumnName("NGAYTAO");

                    b.Property<string>("Options")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("OPTIONS");

                    b.Property<TimeOnly?>("Thoigian")
                        .HasColumnType("time")
                        .HasColumnName("thoigian");

                    b.HasKey("Mabuoihoc")
                        .HasName("PK__BUOIHOC__83505C5952BB8F78");

                    b.HasIndex("Malophoc");

                    b.ToTable("BUOIHOC", (string)null);
                });

            modelBuilder.Entity("DA_Framewrok.Models.Cauhoithithu", b =>
                {
                    b.Property<int>("Macauhoi")
                        .HasColumnType("int")
                        .HasColumnName("MACAUHOI");

                    b.Property<string>("Dapan")
                        .HasColumnType("text")
                        .HasColumnName("DAPAN");

                    b.Property<string>("De")
                        .HasColumnType("text")
                        .HasColumnName("DE");

                    b.Property<string>("Luachon1")
                        .HasColumnType("text")
                        .HasColumnName("LUACHON1");

                    b.Property<string>("Luachon2")
                        .HasColumnType("text")
                        .HasColumnName("LUACHON2");

                    b.Property<string>("Luachon3")
                        .HasColumnType("text")
                        .HasColumnName("LUACHON3");

                    b.Property<string>("Luachon4")
                        .HasColumnType("text")
                        .HasColumnName("LUACHON4");

                    b.HasKey("Macauhoi")
                        .HasName("PK__CAUHOITH__DCF1CAB7D1E32C12");

                    b.ToTable("CAUHOITHITHU", (string)null);
                });

            modelBuilder.Entity("DA_Framewrok.Models.Cautraloi", b =>
                {
                    b.Property<int>("Malanthi")
                        .HasColumnType("int")
                        .HasColumnName("MALANTHI");

                    b.Property<int>("Macauhoi")
                        .HasColumnType("int")
                        .HasColumnName("MACAUHOI");

                    b.Property<string>("Cautraloi1")
                        .HasColumnType("text")
                        .HasColumnName("CAUTRALOI");

                    b.HasKey("Malanthi", "Macauhoi")
                        .HasName("pk_ctl");

                    b.HasIndex("Macauhoi");

                    b.ToTable("CAUTRALOI", (string)null);
                });

            modelBuilder.Entity("DA_Framewrok.Models.Giaovien", b =>
                {
                    b.Property<int>("Magiaovien")
                        .HasColumnType("int")
                        .HasColumnName("MAGIAOVIEN");

                    b.Property<string>("Anhdaidien")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("ANHDAIDIEN");

                    b.Property<string>("Diachi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DIACHI");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Matkhau")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("MATKHAU");

                    b.Property<DateOnly?>("Ngaysinh")
                        .HasColumnType("date")
                        .HasColumnName("NGAYSINH");

                    b.Property<string>("Quoctich")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("QUOCTICH");

                    b.Property<string>("Sodienthoai")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("SODIENTHOAI");

                    b.Property<string>("Tengiaovien")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TENGIAOVIEN");

                    b.Property<string>("Tinhtrang")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("TINHTRANG");

                    b.HasKey("Magiaovien")
                        .HasName("PK__GIAOVIEN__C509E6AD3FE69D86");

                    b.ToTable("GIAOVIEN", (string)null);
                });

            modelBuilder.Entity("DA_Framewrok.Models.Hocvien", b =>
                {
                    b.Property<int>("Mahocvien")
                        .HasColumnType("int")
                        .HasColumnName("MAHOCVIEN");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Matkhau")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("MATKHAU");

                    b.Property<DateOnly?>("Ngaysinh")
                        .HasColumnType("date")
                        .HasColumnName("NGAYSINH");

                    b.Property<string>("Sodienthoai")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("SODIENTHOAI");

                    b.Property<string>("Tenhocvien")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TENHOCVIEN");

                    b.Property<string>("Tinhtrang")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("TINHTRANG");

                    b.HasKey("Mahocvien")
                        .HasName("PK__HOCVIEN__1A8447F180723113");

                    b.ToTable("HOCVIEN", (string)null);
                });

            modelBuilder.Entity("DA_Framewrok.Models.Hocvienthuoclophoc", b =>
                {
                    b.Property<int>("Mahocvien")
                        .HasColumnType("int")
                        .HasColumnName("MAHOCVIEN");

                    b.Property<int>("Malophoc")
                        .HasColumnType("int")
                        .HasColumnName("MALOPHOC");

                    b.Property<int>("Makhoahoc")
                        .HasColumnType("int")
                        .HasColumnName("MAKHOAHOC");

                    b.HasKey("Mahocvien", "Malophoc", "Makhoahoc")
                        .HasName("pk_hvtl");

                    b.HasIndex("Makhoahoc");

                    b.HasIndex("Malophoc");

                    b.ToTable("HOCVIENTHUOCLOPHOC", (string)null);
                });

            modelBuilder.Entity("DA_Framewrok.Models.Khoahoc", b =>
                {
                    b.Property<int>("Makhoahoc")
                        .HasColumnType("int")
                        .HasColumnName("MAKHOAHOC");

                    b.Property<string>("Anhkhoahoc")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ANHKHOAHOC");

                    b.Property<double?>("Giakhoahoc")
                        .HasColumnType("float")
                        .HasColumnName("GIAKHOAHOC");

                    b.Property<string>("Loaikhoahoc")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("LOAIKHOAHOC");

                    b.Property<string>("Mota")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MOTA");

                    b.Property<string>("Tenkhoahoc")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("TENKHOAHOC");

                    b.Property<string>("Thoiluong")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("THOILUONG");

                    b.Property<string>("Trangthai")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("TRANGTHAI");

                    b.HasKey("Makhoahoc")
                        .HasName("PK__KHOAHOC__9E20788D254EC373");

                    b.ToTable("KHOAHOC", (string)null);
                });

            modelBuilder.Entity("DA_Framewrok.Models.Khoahocchitiet", b =>
                {
                    b.Property<int>("Makhoahoc")
                        .HasColumnType("int")
                        .HasColumnName("MAKHOAHOC");

                    b.Property<string>("Doituong")
                        .HasColumnType("text")
                        .HasColumnName("DOITUONG");

                    b.Property<string>("Muctieu")
                        .HasColumnType("text")
                        .HasColumnName("MUCTIEU");

                    b.Property<string>("Noidung")
                        .HasColumnType("text")
                        .HasColumnName("NOIDUNG");

                    b.Property<string>("Thoiluongkhoahoc")
                        .HasColumnType("text")
                        .HasColumnName("THOILUONGKHOAHOC");

                    b.HasKey("Makhoahoc")
                        .HasName("PK__KHOAHOCC__9E20788D0800ADF8");

                    b.ToTable("KHOAHOCCHITIET", (string)null);
                });

            modelBuilder.Entity("DA_Framewrok.Models.Lichhoccualop", b =>
                {
                    b.Property<int>("Malichhoc")
                        .HasColumnType("int")
                        .HasColumnName("MALICHHOC");

                    b.Property<TimeOnly?>("Giobatdau")
                        .HasColumnType("time")
                        .HasColumnName("GIOBATDAU");

                    b.Property<TimeOnly?>("Gioketthuc")
                        .HasColumnType("time")
                        .HasColumnName("GIOKETTHUC");

                    b.Property<int?>("Makhoahoc")
                        .HasColumnType("int")
                        .HasColumnName("MAKHOAHOC");

                    b.Property<int?>("Malophoc")
                        .HasColumnType("int")
                        .HasColumnName("MALOPHOC");

                    b.Property<string>("Thu")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("THU");

                    b.HasKey("Malichhoc")
                        .HasName("PK__LICHHOCC__6D42C8F33A961049");

                    b.HasIndex("Makhoahoc");

                    b.HasIndex("Malophoc");

                    b.ToTable("LICHHOCCUALOP", (string)null);
                });

            modelBuilder.Entity("DA_Framewrok.Models.Lophoc", b =>
                {
                    b.Property<int>("Malophoc")
                        .HasColumnType("int")
                        .HasColumnName("MALOPHOC");

                    b.Property<int?>("Magiaovien")
                        .HasColumnType("int")
                        .HasColumnName("MAGIAOVIEN");

                    b.Property<int?>("Makhoahoc")
                        .HasColumnType("int")
                        .HasColumnName("MAKHOAHOC");

                    b.Property<int?>("Siso")
                        .HasColumnType("int")
                        .HasColumnName("SISO");

                    b.Property<string>("Tenlophoc")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("TENLOPHOC");

                    b.Property<DateOnly?>("Thoigianbatdau")
                        .HasColumnType("date")
                        .HasColumnName("THOIGIANBATDAU");

                    b.Property<DateOnly?>("Thoigianketthuc")
                        .HasColumnType("date")
                        .HasColumnName("THOIGIANKETTHUC");

                    b.Property<string>("Tinhtranglophoc")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("TINHTRANGLOPHOC");

                    b.HasKey("Malophoc")
                        .HasName("PK__LOPHOC__3680BCE2EDE9B863");

                    b.HasIndex("Magiaovien");

                    b.HasIndex("Makhoahoc");

                    b.ToTable("LOPHOC", (string)null);
                });

            modelBuilder.Entity("DA_Framewrok.Models.Quantrivien", b =>
                {
                    b.Property<int>("Maquantrivien")
                        .HasColumnType("int")
                        .HasColumnName("MAQUANTRIVIEN");

                    b.Property<string>("Matkhau")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("MATKHAU");

                    b.Property<string>("Taikhoan")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("TAIKHOAN");

                    b.HasKey("Maquantrivien")
                        .HasName("PK__QUANTRIV__0D5638969AAE4A29");

                    b.ToTable("QUANTRIVIEN", (string)null);
                });

            modelBuilder.Entity("DA_Framewrok.Models.Solanthi", b =>
                {
                    b.Property<int>("Malanthi")
                        .HasColumnType("int")
                        .HasColumnName("MALANTHI");

                    b.Property<int?>("Mahocvien")
                        .HasColumnType("int")
                        .HasColumnName("MAHOCVIEN");

                    b.Property<DateOnly?>("Ngaythi")
                        .HasColumnType("date")
                        .HasColumnName("NGAYTHI");

                    b.Property<int?>("Socaudung")
                        .HasColumnType("int")
                        .HasColumnName("SOCAUDUNG");

                    b.HasKey("Malanthi")
                        .HasName("PK__SOLANTHI__88DDE28F2EA4DD91");

                    b.HasIndex("Mahocvien");

                    b.ToTable("SOLANTHI", (string)null);
                });

            modelBuilder.Entity("DA_Framewrok.Models.Thanhtoan", b =>
                {
                    b.Property<int>("Mathanhtoan")
                        .HasColumnType("int")
                        .HasColumnName("MATHANHTOAN");

                    b.Property<int?>("Mahocvien")
                        .HasColumnType("int")
                        .HasColumnName("MAHOCVIEN");

                    b.Property<int?>("Makhoahoc")
                        .HasColumnType("int")
                        .HasColumnName("MAKHOAHOC");

                    b.Property<int?>("Malophoc")
                        .HasColumnType("int")
                        .HasColumnName("MALOPHOC");

                    b.Property<DateTime?>("Thoigianthanhtoan")
                        .HasColumnType("datetime")
                        .HasColumnName("THOIGIANTHANHTOAN");

                    b.Property<double?>("Tongtienthanhtoan")
                        .HasColumnType("float")
                        .HasColumnName("TONGTIENTHANHTOAN");

                    b.HasKey("Mathanhtoan")
                        .HasName("PK__THANHTOA__E5D8225CB730DDFA");

                    b.HasIndex("Mahocvien");

                    b.HasIndex("Makhoahoc");

                    b.HasIndex("Malophoc");

                    b.ToTable("THANHTOAN", (string)null);
                });

            modelBuilder.Entity("DA_Framewrok.Models.Thongtinlophoc", b =>
                {
                    b.Property<int>("Mathongtin")
                        .HasColumnType("int")
                        .HasColumnName("MATHONGTIN");

                    b.Property<int?>("Malophoc")
                        .HasColumnType("int")
                        .HasColumnName("MALOPHOC");

                    b.Property<DateOnly?>("Ngaytao")
                        .HasColumnType("date")
                        .HasColumnName("NGAYTAO");

                    b.Property<string>("Noidungthong")
                        .HasColumnType("text")
                        .HasColumnName("NOIDUNGTHONG");

                    b.Property<string>("Tendinhkem")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TENDINHKEM");

                    b.Property<string>("Tieude")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TIEUDE");

                    b.HasKey("Mathongtin")
                        .HasName("PK__THONGTIN__3C716A34248787F3");

                    b.HasIndex("Malophoc");

                    b.ToTable("THONGTINLOPHOC", (string)null);
                });

            modelBuilder.Entity("DA_Framewrok.Models.Buoihoc", b =>
                {
                    b.HasOne("DA_Framewrok.Models.Lophoc", "MalophocNavigation")
                        .WithMany("Buoihocs")
                        .HasForeignKey("Malophoc")
                        .HasConstraintName("fk_bhon_lh");

                    b.Navigation("MalophocNavigation");
                });

            modelBuilder.Entity("DA_Framewrok.Models.Cautraloi", b =>
                {
                    b.HasOne("DA_Framewrok.Models.Cauhoithithu", "MacauhoiNavigation")
                        .WithMany("Cautralois")
                        .HasForeignKey("Macauhoi")
                        .IsRequired()
                        .HasConstraintName("fk_tl_slt");

                    b.HasOne("DA_Framewrok.Models.Solanthi", "MalanthiNavigation")
                        .WithMany("Cautralois")
                        .HasForeignKey("Malanthi")
                        .IsRequired()
                        .HasConstraintName("fk_tl_ch");

                    b.Navigation("MacauhoiNavigation");

                    b.Navigation("MalanthiNavigation");
                });

            modelBuilder.Entity("DA_Framewrok.Models.Hocvienthuoclophoc", b =>
                {
                    b.HasOne("DA_Framewrok.Models.Hocvien", "MahocvienNavigation")
                        .WithMany("Hocvienthuoclophocs")
                        .HasForeignKey("Mahocvien")
                        .IsRequired()
                        .HasConstraintName("fk_hvl_hv");

                    b.HasOne("DA_Framewrok.Models.Khoahoc", "MakhoahocNavigation")
                        .WithMany("Hocvienthuoclophocs")
                        .HasForeignKey("Makhoahoc")
                        .IsRequired()
                        .HasConstraintName("fk_hvl_khoahoc");

                    b.HasOne("DA_Framewrok.Models.Lophoc", "MalophocNavigation")
                        .WithMany("Hocvienthuoclophocs")
                        .HasForeignKey("Malophoc")
                        .IsRequired()
                        .HasConstraintName("fk_hvl_lophoc");

                    b.Navigation("MahocvienNavigation");

                    b.Navigation("MakhoahocNavigation");

                    b.Navigation("MalophocNavigation");
                });

            modelBuilder.Entity("DA_Framewrok.Models.Khoahocchitiet", b =>
                {
                    b.HasOne("DA_Framewrok.Models.Khoahoc", "MakhoahocNavigation")
                        .WithOne("Khoahocchitiet")
                        .HasForeignKey("DA_Framewrok.Models.Khoahocchitiet", "Makhoahoc")
                        .IsRequired()
                        .HasConstraintName("fk_khct_kh");

                    b.Navigation("MakhoahocNavigation");
                });

            modelBuilder.Entity("DA_Framewrok.Models.Lichhoccualop", b =>
                {
                    b.HasOne("DA_Framewrok.Models.Khoahoc", "MakhoahocNavigation")
                        .WithMany("Lichhoccualops")
                        .HasForeignKey("Makhoahoc")
                        .HasConstraintName("fk_lhcl_khoahoc");

                    b.HasOne("DA_Framewrok.Models.Lophoc", "MalophocNavigation")
                        .WithMany("Lichhoccualops")
                        .HasForeignKey("Malophoc")
                        .HasConstraintName("fk_lhct_lophoc");

                    b.Navigation("MakhoahocNavigation");

                    b.Navigation("MalophocNavigation");
                });

            modelBuilder.Entity("DA_Framewrok.Models.Lophoc", b =>
                {
                    b.HasOne("DA_Framewrok.Models.Giaovien", "MagiaovienNavigation")
                        .WithMany("Lophocs")
                        .HasForeignKey("Magiaovien")
                        .HasConstraintName("fk_lh_gv");

                    b.HasOne("DA_Framewrok.Models.Khoahoc", "MakhoahocNavigation")
                        .WithMany("Lophocs")
                        .HasForeignKey("Makhoahoc")
                        .HasConstraintName("fk_lh_kh");

                    b.Navigation("MagiaovienNavigation");

                    b.Navigation("MakhoahocNavigation");
                });

            modelBuilder.Entity("DA_Framewrok.Models.Solanthi", b =>
                {
                    b.HasOne("DA_Framewrok.Models.Hocvien", "MahocvienNavigation")
                        .WithMany("Solanthis")
                        .HasForeignKey("Mahocvien")
                        .HasConstraintName("fk_slt_hv");

                    b.Navigation("MahocvienNavigation");
                });

            modelBuilder.Entity("DA_Framewrok.Models.Thanhtoan", b =>
                {
                    b.HasOne("DA_Framewrok.Models.Hocvien", "MahocvienNavigation")
                        .WithMany("Thanhtoans")
                        .HasForeignKey("Mahocvien")
                        .HasConstraintName("fk_tt_hv");

                    b.HasOne("DA_Framewrok.Models.Khoahoc", "MakhoahocNavigation")
                        .WithMany("Thanhtoans")
                        .HasForeignKey("Makhoahoc")
                        .HasConstraintName("fk_tt_kh");

                    b.HasOne("DA_Framewrok.Models.Lophoc", "MalophocNavigation")
                        .WithMany("Thanhtoans")
                        .HasForeignKey("Malophoc")
                        .HasConstraintName("fk_tt_lh");

                    b.Navigation("MahocvienNavigation");

                    b.Navigation("MakhoahocNavigation");

                    b.Navigation("MalophocNavigation");
                });

            modelBuilder.Entity("DA_Framewrok.Models.Thongtinlophoc", b =>
                {
                    b.HasOne("DA_Framewrok.Models.Lophoc", "MalophocNavigation")
                        .WithMany("Thongtinlophocs")
                        .HasForeignKey("Malophoc")
                        .HasConstraintName("fk_ttl_lh");

                    b.Navigation("MalophocNavigation");
                });

            modelBuilder.Entity("DA_Framewrok.Models.Cauhoithithu", b =>
                {
                    b.Navigation("Cautralois");
                });

            modelBuilder.Entity("DA_Framewrok.Models.Giaovien", b =>
                {
                    b.Navigation("Lophocs");
                });

            modelBuilder.Entity("DA_Framewrok.Models.Hocvien", b =>
                {
                    b.Navigation("Hocvienthuoclophocs");

                    b.Navigation("Solanthis");

                    b.Navigation("Thanhtoans");
                });

            modelBuilder.Entity("DA_Framewrok.Models.Khoahoc", b =>
                {
                    b.Navigation("Hocvienthuoclophocs");

                    b.Navigation("Khoahocchitiet");

                    b.Navigation("Lichhoccualops");

                    b.Navigation("Lophocs");

                    b.Navigation("Thanhtoans");
                });

            modelBuilder.Entity("DA_Framewrok.Models.Lophoc", b =>
                {
                    b.Navigation("Buoihocs");

                    b.Navigation("Hocvienthuoclophocs");

                    b.Navigation("Lichhoccualops");

                    b.Navigation("Thanhtoans");

                    b.Navigation("Thongtinlophocs");
                });

            modelBuilder.Entity("DA_Framewrok.Models.Solanthi", b =>
                {
                    b.Navigation("Cautralois");
                });
#pragma warning restore 612, 618
        }
    }
}
